### ISSUE TITLE
rtmp support

### ISSUE THREAD

**Issue by Richzendy** [emaxsaun/jwbox#1]
First all, thank you for sharing,

I've change the line 84 from:

```
file: "http://content.bitsontherun.com/videos/I8lldC6V-8ULb9uN9.mp4",
```

to:

```
file: theFile,
```

To work with rtmp streaming, maybe you should consider make jwbox with rtmp support, you can see my code working on:

http://www.nascarmexico.com.mx/v8/streaming/  (work in progress)

**Comment by emaxsaun** [comment]
Hi,

That is a good idea. I originally did it that way to make it so that there
was a file present on load, but you are right, the blank mp4 file is not
needed. I will update it, thanks for posting this suggestion.

Best,
-Ethan
